@startuml

title Punto de vista arquitectura JAVA EE.


Package Controller{
class FacesServlet
}

Package Model{
class Service
class  ManagedBean{
 -@inject service
}
class Entity
class Dao
}
ManagedBean --> Service
Service --> Entity
Service --> Dao

Package View{
class Facelets
class JSFComponent
class XHTML
Facelets --> JSFComponent
Facelets --> XHTML
}

Controller --> View
Controller --> Model
View --> Model
@enduml