@startuml

title Punto de vista arquitectura JAVA EE.

Package Controller{
class FacesServlet
}

Package Model{
class  ManagedBean<<View>>
class Service<<Controller, Inject>>
class Entity<<Model>>
class EJB<<View>>
class Dao<<View>>
}
ManagedBean --> Service
Service --> Entity
Service --> Dao
Service --> EJB

Package View{
class Facelets<<Controller>>
class JSFComponent<<Model>>
class XHTML<<View>>
Facelets --> JSFComponent
Facelets --> XHTML
}

Controller --> View
Controller --> Model
View --> Model
@enduml